// Code generated by sails-client-gen-v2. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct BrewingRepOracleClientProgram;

impl BrewingRepOracleClientProgram {
    pub const ROUTE_ID_REPUTATION_ORACLE: u8 = 1;
}

impl sails_rs::client::Program for BrewingRepOracleClientProgram {}

pub trait BrewingRepOracleClient {
    type Env: sails_rs::client::GearEnv;
    fn reputation_oracle(
        &self,
    ) -> sails_rs::client::Service<reputation_oracle::ReputationOracleImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> BrewingRepOracleClient
    for sails_rs::client::Actor<BrewingRepOracleClientProgram, E>
{
    type Env = E;
    fn reputation_oracle(
        &self,
    ) -> sails_rs::client::Service<reputation_oracle::ReputationOracleImpl, Self::Env> {
        self.service(BrewingRepOracleClientProgram::ROUTE_ID_REPUTATION_ORACLE)
    }
}
pub trait BrewingRepOracleClientCtors {
    type Env: sails_rs::client::GearEnv;
    /// Constructor.
    ///
    /// - `owner`: defaults to `msg::source()` (the deploying wallet).
    /// - `query_fee`: defaults to `DEFAULT_QUERY_FEE` (0.1 VARA).
    fn init(
        self,
        owner: Option<ActorId>,
        query_fee: Option<u128>,
    ) -> sails_rs::client::PendingCtor<BrewingRepOracleClientProgram, io::Init, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> BrewingRepOracleClientCtors
    for sails_rs::client::Deployment<BrewingRepOracleClientProgram, E>
{
    type Env = E;
    fn init(
        self,
        owner: Option<ActorId>,
        query_fee: Option<u128>,
    ) -> sails_rs::client::PendingCtor<BrewingRepOracleClientProgram, io::Init, Self::Env> {
        self.pending_ctor((owner, query_fee))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Init (owner: super::Option<ActorId, >, query_fee: super::Option<u128, >) -> (), 0);
}

pub mod reputation_oracle {
    use super::*;

    /// Reputation score returned to callers of GetScore / QueryScore.
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct ReputationScore {
        pub worker: ActorId,
        pub completed: u32,
        pub disputed: u32,
        /// Basis points (0-10 000). 10 000 if the worker has no history.
        pub success_rate: u32,
        pub total_value: u128,
    }

    pub trait ReputationOracle {
        type Env: sails_rs::client::GearEnv;
        /// Add an approved source (e.g., a job board). Owner only.
        fn add_approved_source(
            &mut self,
            source: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddApprovedSource, Self::Env>;
        /// Return total VARA fees collected but not yet withdrawn.
        fn collected_fees(&self) -> sails_rs::client::PendingCall<io::CollectedFees, Self::Env>;
        /// Query a worker's reputation score. Charges `query_fee` VARA.
        ///
        /// - Underpayment: panics `"InsufficientFee"` — Gear auto-refunds attached value on panic.
        /// - Overpayment: excess returned atomically via `CommandReply::with_value`.
        /// - Exact payment: no refund needed.
        fn get_score(
            &mut self,
            worker: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetScore, Self::Env>;
        /// Check if an address is an approved submission source.
        fn is_approved_source(
            &self,
            source: ActorId,
        ) -> sails_rs::client::PendingCall<io::IsApprovedSource, Self::Env>;
        /// Return the program owner.
        fn owner(&self) -> sails_rs::client::PendingCall<io::Owner, Self::Env>;
        /// Return the current per-query fee in planck-units.
        fn query_fee(&self) -> sails_rs::client::PendingCall<io::QueryFee, Self::Env>;
        /// Return a worker's reputation score — free read, no fee charged.
        fn query_score(
            &self,
            worker: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryScore, Self::Env>;
        /// Record a job completion (or dispute) for a worker.
        ///
        /// Caller must be an approved source OR the owner.
        /// Workers cannot self-report (worker != msg::source()).
        fn record_completion(
            &mut self,
            worker: ActorId,
            succeeded: bool,
            value: u128,
        ) -> sails_rs::client::PendingCall<io::RecordCompletion, Self::Env>;
        /// Remove an approved source. Owner only.
        fn remove_approved_source(
            &mut self,
            source: ActorId,
        ) -> sails_rs::client::PendingCall<io::RemoveApprovedSource, Self::Env>;
        /// Update the per-query fee. Owner only.
        fn set_query_fee(
            &mut self,
            fee: u128,
        ) -> sails_rs::client::PendingCall<io::SetQueryFee, Self::Env>;
        /// Withdraw accumulated fees to the owner wallet. Owner only.
        /// Panics `"NotOwner"` if caller is not the owner.
        fn withdraw_fees(&mut self) -> sails_rs::client::PendingCall<io::WithdrawFees, Self::Env>;
    }

    pub struct ReputationOracleImpl;

    impl sails_rs::client::Identifiable for ReputationOracleImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([227, 170, 40, 167, 218, 44, 115, 232]);
    }

    impl<E: sails_rs::client::GearEnv> ReputationOracle
        for sails_rs::client::Service<ReputationOracleImpl, E>
    {
        type Env = E;
        fn add_approved_source(
            &mut self,
            source: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddApprovedSource, Self::Env> {
            self.pending_call((source,))
        }
        fn collected_fees(&self) -> sails_rs::client::PendingCall<io::CollectedFees, Self::Env> {
            self.pending_call(())
        }
        fn get_score(
            &mut self,
            worker: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetScore, Self::Env> {
            self.pending_call((worker,))
        }
        fn is_approved_source(
            &self,
            source: ActorId,
        ) -> sails_rs::client::PendingCall<io::IsApprovedSource, Self::Env> {
            self.pending_call((source,))
        }
        fn owner(&self) -> sails_rs::client::PendingCall<io::Owner, Self::Env> {
            self.pending_call(())
        }
        fn query_fee(&self) -> sails_rs::client::PendingCall<io::QueryFee, Self::Env> {
            self.pending_call(())
        }
        fn query_score(
            &self,
            worker: ActorId,
        ) -> sails_rs::client::PendingCall<io::QueryScore, Self::Env> {
            self.pending_call((worker,))
        }
        fn record_completion(
            &mut self,
            worker: ActorId,
            succeeded: bool,
            value: u128,
        ) -> sails_rs::client::PendingCall<io::RecordCompletion, Self::Env> {
            self.pending_call((worker, succeeded, value))
        }
        fn remove_approved_source(
            &mut self,
            source: ActorId,
        ) -> sails_rs::client::PendingCall<io::RemoveApprovedSource, Self::Env> {
            self.pending_call((source,))
        }
        fn set_query_fee(
            &mut self,
            fee: u128,
        ) -> sails_rs::client::PendingCall<io::SetQueryFee, Self::Env> {
            self.pending_call((fee,))
        }
        fn withdraw_fees(&mut self) -> sails_rs::client::PendingCall<io::WithdrawFees, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AddApprovedSource (source: ActorId) -> bool, 0, <super::ReputationOracleImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(CollectedFees () -> u128, 1, <super::ReputationOracleImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(GetScore (worker: ActorId) -> super::ReputationScore, 2, <super::ReputationOracleImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(IsApprovedSource (source: ActorId) -> bool, 3, <super::ReputationOracleImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Owner () -> ActorId, 4, <super::ReputationOracleImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(QueryFee () -> u128, 5, <super::ReputationOracleImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(QueryScore (worker: ActorId) -> super::ReputationScore, 6, <super::ReputationOracleImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(RecordCompletion (worker: ActorId, succeeded: bool, value: u128) -> bool, 7, <super::ReputationOracleImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(RemoveApprovedSource (source: ActorId) -> bool, 8, <super::ReputationOracleImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SetQueryFee (fee: u128) -> bool, 9, <super::ReputationOracleImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(WithdrawFees () -> u128, 10, <super::ReputationOracleImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[sails_rs::sails_type(crate = sails_rs)]
        #[derive(PartialEq, Debug)]
        pub enum ReputationOracleEvents {
            #[codec(index = 0)]
            ApprovedSourceAdded { source: ActorId },
            #[codec(index = 1)]
            ApprovedSourceRemoved { source: ActorId },
            #[codec(index = 2)]
            CompletionRecorded {
                worker: ActorId,
                succeeded: bool,
                value: u128,
            },
            #[codec(index = 3)]
            FeesWithdrawn { to: ActorId, amount: u128 },
            #[codec(index = 4)]
            QueryFeeUpdated { new_fee: u128 },
            #[codec(index = 5)]
            ScoreQueried {
                worker: ActorId,
                querier: ActorId,
                fee_paid: u128,
            },
        }

        impl ReputationOracleEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::ApprovedSourceAdded { .. } => 0,
                    Self::ApprovedSourceRemoved { .. } => 1,
                    Self::CompletionRecorded { .. } => 2,
                    Self::FeesWithdrawn { .. } => 3,
                    Self::QueryFeeUpdated { .. } => 4,
                    Self::ScoreQueried { .. } => 5,
                }
            }
        }

        impl sails_rs::client::Event for ReputationOracleEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for ReputationOracleEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <ReputationOracleImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for ReputationOracleImpl {
            type Event = ReputationOracleEvents;
        }
    }
}
